name: .NET Core

on:
 push:
  branches: [ main ]

jobs:
 build:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2

  - name: Setup .NET Core
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '6.0'

  - name: Install dependencies
    run: dotnet restore

  - name: Build
    run: dotnet build --configuration Release --no-restore

  - name: Test
    run: dotnet test --no-restore --verbosity normal

  - name: Deploy
    run: |
      ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << EOF
      cd /var/www/netwix
      git pull
      pm2 restart ecosystem.config.js
      EOF
